INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./outputs"

# Evaluation datasets
GRABCUT_PATH: "./data/datasets/GrabCut"
BERKELEY_PATH: "./data/datasets/Berkeley"
DAVIS_PATH: "./data/datasets/DAVIS"
COCO_MVAL_PATH: "./data/datasets/COCO_MVal"
BraTS_PATH: "./data/datasets/BraTS20"
ssTEM_PATH: "./data/datasets/ssTEM"
OAIZIB_PATH: "./data/datasets/OAI-ZIB/iseg_slices"
OAI_PATH: "./data/datasets/OAI"
HARD_PATH: "./data/datasets/HARD"

# Train datasets
SBD_PATH: "./data/datasets/SBD"
COCO_PATH: "./data/datasets/COCO_2017"
LVIS_v1_PATH: "./data/datasets/COCO_2017"
OPENIMAGES_PATH: "./data/datasetssets/OpenImages"
PASCALVOC_PATH: "./data/datasets/PascalVOC"
ADE20K_PATH: "./data/datasetssets/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./weights/pretrained/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./weights/pretrained/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./weights/pretrained/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./weights/pretrained/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W64: "./weights/pretrained/hrnetv2_w64_imagenet_pretrained.pth"
  MIT_B5: "./weights/pretrained/mit_b5_converted.pth"
  MIT_B4: "./weights/pretrained/mit_b4_converted.pth"
  MIT_B3: "./weights/pretrained/mit_b3_converted.pth"
  MIT_B2: "./weights/pretrained/mit_b2_converted.pth"
  MIT_B1: "./weights/pretrained/mit_b1_converted.pth"
  MIT_B0: "./weights/pretrained/mit_b0_converted.pth"
  HRF_BASE: "./weights/pretrained/hrt_base.pth"
  SWIN_BASE: "./weights/pretrained/swin_base_patch4_window12_384_22k.pth"
  SWIN_LARGE: "./weights/pretrained/swin_large_patch4_window12_384_22k.pth"
  MAE_BASE: "./weights/pretrained/mae_pretrain_vit_base.pth"
  MAE_LARGE: "./weights/pretrained/mae_pretrain_vit_large.pth"
  MAE_HUGE: "./weights/pretrained/mae_pretrain_vit_huge.pth"
  MAE_BASE_URL: "https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth"
  MAE_LARGE_URL: "https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_large.pth"
  MAE_HUGE_URL: "https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_huge.pth"
